name: Security Testing

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:

permissions:
  contents: read

jobs:
  security_audit:
    name: Security & Code Quality Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Audit Check
        runs: cargo audit
        
      - name: Deny Check
        runs: cargo deny check
